### ISSUE TITLE
Nativescript 8.x porting

### ISSUE THREAD

**Issue by biospank** [DeepakArora76/nativescript-dna-netservices-ns-6.0#14]
Hey @DeepakArora76,
I really appreciate your work on this plugin and I've been using it successfully on my project up to version 6.x.
With release of Nativescript 8 the core team has changed the way to refer **tns-core-modules** to **@nativescript/core** causing the plugin to stop to work.

Is there any plan to port this plugin to Nativescript 8.x?

Cheers

**Comment by DeepakArora76** [comment]
@biospank I will give it a try over the weekend. It could take some time.

**Comment by biospank** [comment]
Great! no rush take your time ;)

**Comment by DeepakArora76** [comment]
@biospank, Please use the latest release 2.0.1 of the plugin. It is updated to use NativeScript 8.0 framework.

Kindly read the updated documentation. Also, refer to https://github.com/DeepakArora76/HelloNetServices/tree/master for any practical implementation hints for iOS and Android.

I am sure the demo application "HelloNetServices" gives you all needed clue. I have tested it with Android and iOS devices.

If you still have the problem, please reopen the issue.

```
For record, the old branch/repo is named to nativescript-dna-netservices-ns-6.0.

The new repo which is based on NativeScript version 8.0 is nativescript-dna-netservices.
```
