### ISSUE TITLE
TypeError: Cannot read property 'druk' of undefined

### ISSUE THREAD

**Issue by danielgeri** [DeepakArora76/nativescript-dna-netservices-ns-6.0#2]
Hello - I have installed the plugin and am running `tns preview`. When I do so and call either `searchForBrowsableDomains()` or `searchForServicesOfTypeInDomain()` I get the following error:
```
TypeError: Cannot read property 'druk' of undefined
```
I have also tried running this on the android simulator via `tns run android` and am getting:
```
JS: ERROR TypeError: com.github.druk.rx2dnssd.Rx2DnssdBindable is not a constructor
```
My guess is that I'm missing a step in installation but I'm not sure what it is. Any guidance? Thanks!

**Comment by DeepakArora76** [comment]
I am unable to replicate the issue in my development environment. Kindly make sure that you have Java 8 installed and update the Android plugin to latest version.

**Comment by danielgeri** [comment]
ok thanks!
